image: node:10.15.3-alpine

# services:
#   - python:3.6

before_script:
  - apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ \
    && yarn
    && apk del build-dependencies

build:
  script:
    - yarn build

