image: node:10.15.3-alpine

stages:
  - build

build and deploy lingo:
  stage: build
  script:
    - 'apk --no-cache --virtual build-dependencies add python make g++ && yarn && apk del build-dependencies'
    - 'apk -Uuv add groff less python py-pip'
    - 'pip install awscli'
    - 'apk --purge -v del py-pip'
    - 'rm /var/cache/apk/*'
    - yarn ng build --prod
    - if [[ $CI_COMMIT_REF_NAME == 'test' ]]; then
        BUILD_BUCKET=lingo-test-build
      elif [[ $CI_COMMIT_REF_NAME == 'app1' ]]; then
        BUILD_BUCKET=lingo-app1-build
      elif [[ $CI_COMMIT_REF_NAME == 'app2' ]]; then
        BUILD_BUCKET=lingo-app2-build
      elif [[ $CI_COMMIT_REF_NAME == 'lingo' ]]; then
        BUILD_BUCKET=lingo-root-build
      fi
    - aws s3 rm s3://$BUILD_BUCKET/dist --recursive
    - aws s3 rm s3://$BUILD_BUCKET/server --recursive
    - aws s3 sync ./dist s3://$BUILD_BUCKET/dist
    - aws s3 sync ./server s3://$BUILD_BUCKET/server
    - aws s3 cp ./package.json s3://$BUILD_BUCKET/package.json



