before_script:
  - apt-get update; apt-get install curl -y
  - curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
  - sudo yum install yarn -y

build:
  script:
    - yarn
    - yarn build
