before_script:
  - apk add --update curl
  # - sudo yup install curl -y
  # - curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
  # - sudo yum install yarn -y

build:
  script:
    - yarn
    - yarn build
