image: node:10.15.3-alpine

# services:
#   - python:3.6

before_script:
  - 'apk --no-cache --virtual build-dependencies add python make g++ && yarn && apk del build-dependencies'
  - 'apk -Uuv add groff less python py-pip'
  - 'pip install awscli'
  - 'apk --purge -v del py-pip'
  - 'rm /var/cache/apk/*'

build:
  script:
    - echo $CI_COMMIT_REF_NAME
    - yarn build
    - aws s3 sync ./dist s3://screener2builds/dist
    - aws s3 sync ./server s3://screener2builds/server
    - aws s3 cp ./package.json s3://screener2builds/package.json


