---
Description: CloudFormation template for creating an ec2 instance
Parameters:
  KeyName:
    Description: Key Pair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: xxx-xxx
  VPC:
    Type: AWS::EC2::VPC::Id
    Default: givevpcid
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Default: givesubnetid
  InstanceType:
    Description: Select one of the possible instance types
    Type: String
    Default: t2.micro
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Default: givesecuritygroupid
  ImageID:
    Type: AWS::EC2::Image::Id
    Default: ami-0de53d8956e8dcf80
Resources:

# RecordSet:
#   Type: AWS::Route53::RecordSet
#   Properties:
#     AliasTarget:
#       AliasTarget
#     Comment: String
#     Failover: String
#     GeoLocation:
#       GeoLocation
#     HealthCheckId: String
#     HostedZoneId: String
#     HostedZoneName: String
#     MultiValueAnswer: Boolean
#     Name: String
#     Region: String
#     ResourceRecords:
#       - String
#     SetIdentifier: String
#     TTL: String
#     Type: String
#     Weight: Integer
  IamInstanceProfileForServer:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - ec2tos3
      InstanceProfileName: ServerInstanceProfile
  Server:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref:
          IamInstanceProfileForServer
      ImageId:
        Ref: ImageID
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      SecurityGroupIds:
      - Ref: SecurityGroup
      SubnetId:
        Ref: Subnet
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xe
            sudo yum update -y
            sudo wget -O /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
            sudo chmod +x /usr/local/bin/gitlab-runner
            sudo useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash
            sudo gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
            sudo gitlab-runner start
Outputs:
  PublicName:
    Value:
      Fn::GetAtt:
      - Server
      - PublicDnsName
    Description: Public name (connect via SSH)
