---
Description: CloudFormation template for launching the Lingo app
Parameters:
  BuildBucketName:
    AllowedValues:
    - lingo-root-build
    - lingo-app1-build
    - lingo-app2-build
    - lingo-test-build
  SubDomainName:
    AllowedValues:
    - lingo
    - app1
    - app2
    - test
  SSLCertARNForSubdomain:
    Default: Match SSL ARN from ACM with subdomain
    Type: String
  KeyName:
    Description: Key Pair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: xxx-xxx
  VPC:
    Type: AWS::EC2::VPC::Id
    Default: givevpcid
  Subnet1ForLoadBalancer:
    Type: AWS::EC2::Subnet::Id
    Default: givesubnetid
  Subnet2ForLoadBalancer:
    Type: AWS::EC2::Subnet::Id
    Default: givesubnetid
  InstanceType:
    Description: Select one of the possible instance types
    Type: String
    Default: t2.micro
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Default: givesecuritygroupid
  ImageID:
    Type: AWS::EC2::Image::Id
    Default: ami-0de53d8956e8dcf80
  AssessmentDataBucketName:
    Type: String
    Default: Assessment Data Bucket Name

Conditions:
  UseSubdomain:
    Not: [Equals: [Ref: SubDomainName, lingo]]
Resources:
  LingoDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: AssessmentDataBucketName
    DeletionPolicy: Retain

  RecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: lingo.aws.cloud.uiowa.edu.
      RecordSets:
      # Put join function here
      - Name: lingo.aws.cloud.uiowa.edu.
        Type: A
        AliasTarget:
          HostedZoneId:
            Fn::GetAtt:
              LingoLoadBalancer.CanonicalHostedZoneID
          DNSName:
            Fn::GetAtt:
              LingoLoadBalancer.DNSName

  LingoIamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - ec2tos3

  LingoLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: LingoLoadBalancer
      Scheme: internet-facing
      SecurityGroups:
        - Ref: SecurityGroup
      Subnets:
        - Ref: Subnet1ForLoadBalancer
        - Ref: Subnet2ForLoadBalancer
      Type: application

  ListenerForBalancer:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn:
            Ref: SSLCertARNForSubdomain
      DefaultActions:
      - TargetGroupArn:
          Ref: LingoTargetGroup
        Type: forward
      LoadBalancerArn:
        Ref: LingoLoadBalancer
      Port: 443
      Protocol: HTTPS

  LingoTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: LingoGroup1
      Port: 8080
      Protocol: HTTP
      VpcId:
        Ref: VPC

  LingoServerLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId:
        Ref: ImageID
      IamInstanceProfile:
        Ref:
          LingoIamInstanceProfile
      SecurityGroups:
      - Ref: SecurityGroup
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xe
            sudo yum update -y
            sudo yum install git -y
            sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            nvm install 10
            node --version
            curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
            curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
            sudo yum install yarn -y
            cd /home/ec2-user
            echo "export LINGO_BUCKET=${AssessmentDataBucketName}" > ~/lingostartup.sh
            sudo chmod +x ~/lingostartup.sh
            echo "aws s3 cp s3://screener2builds/ . --recursive" >> ~/lingostartup.sh
            echo "yarn" >> ~/lingostartup.sh
            echo "yarn start" >> ~/lingostartup.sh
            sudo cp ~/lingostartup.sh /etc/profile.d/lingostartup.sh
            ~/lingostartup.sh
            # sudo yarn
            # nohup sudo yarn start &

  LingoAutoScaleGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      Tags:
      - Key: Name
        Value: LingoInstance
        PropagateAtLaunch: true
      VPCZoneIdentifier:
        [Ref: Subnet1ForLoadBalancer, Ref: Subnet2ForLoadBalancer]
      LaunchConfigurationName:
        Ref: LingoServerLaunchConfig
      MinSize: '1'
      MaxSize: '1'
      TargetGroupARNs: [Ref: LingoTargetGroup]
