---
Description: CloudFormation template for creating a Lingo GitLab Runner
Parameters:
  KeyName:
    Description: Key Pair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: xxx-xxx
  InstanceType:
    Description: Select one of the possible instance types
    Type: String
    Default: t2.medium
  ImageID:
    Type: AWS::EC2::Image::Id
    Default: ami-0de53d8956e8dcf80
  GitLabUrl:
    Type: String
    Default: https://research-git.uiowa.edu/
  GitLabRegistrationToken:
    Type: String
    Default: GitLab Runner Registration Token
    Description: Get from https://research-git.uiowa.edu/michaelson-lab/language-screener/ScreenerVersion2/settings/ci_cd#js-runners-settings
Resources:
  IamInstanceProfileForRunner:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - ec2tos3
      InstanceProfileName: RunnerInstanceProfile
  RunnerServer:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref:
          IamInstanceProfileForRunner
      ImageId:
        Ref: ImageID
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      SecurityGroupIds:
        - sg-03632539cbcd91af5
      SubnetId:
        subnet-0737a237be02ece05
      Tags:
      - Key: Name
        Value: LingoGitlabRunner
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xe
            yum update -y

            # Install FireEyeHX endpoint
            mkdir ~/FireEye && cd ~/FireEye
            aws s3 cp s3://fire-eye-hx-endpoint/IMAGE_HX_AGENT_LINUX_30.19.0.tgz IMAGE_HX_AGENT_LINUX_30.19.0.tgz
            tar zxvf IMAGE_HX_AGENT_LINUX_30.19.0.tgz
            rpm -ihv xagt-30.19.0-1.el7.x86_64.rpm
            /opt/fireeye/bin/xagt -i agent_config.json
            service xagt start

            amazon-linux-extras install docker -y
            service docker start
            curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh | bash
            yum install gitlab-runner -y
            gitlab-runner register \
                --non-interactive \
                --url ${GitLabUrl} \
                --registration-token ${GitLabRegistrationToken} \
                --executor "docker" \
                --docker-image "node:10.15.3-alpine" \
                --description "Lingo Runner" \
                --tag-list "" \
                --run-untagged="true"
Outputs:
  PublicName:
    Value:
      Fn::GetAtt:
      - RunnerServer
      - PublicDnsName
    Description: Public name (connect via SSH)
